require 'active_support/all'
require 'google/apis/gmail_v1'
require 'googleauth'
require 'googleauth/stores/file_token_store'
require 'fileutils'
require 'open-uri'
require 'addressable/uri'
require 'nokogiri'
require 'typhoeus'
require 'csv'
require 'digest/md5'
require 'mysql2'
require 'sequel'
require 'pdf-reader'
require 'bibtex'
require 'slim'
require 'yaml'
require 'rtesseract'
require 'mini_magick'
require 'parallel'
require 'colorize'
require 'serrano'
require 'write_xlsx'
require 'byebug'

Dir[File.dirname(__FILE__) + "/lib/*.rb"].each{ |file| require file }